# Generated by Django 5.2.13 on 2026-08-29 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def publish_existing_articles(apps, schema_editor):
    Article = apps.get_model('wiki', 'Article')
    Article.objects.all().update(status='published')


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_article_author_article_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at'], 'verbose_name': 'Wiki article', 'verbose_name_plural': 'Wiki articles'},
        ),
        migrations.AddField(
            model_name='article',
            name='moderator_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('published', 'Published'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ArticleRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('introduction', models.CharField(max_length=500)),
                ('body_text', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='articles/revisions/')),
                ('remove_cover', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('moderator_comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='wiki.article')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_revisions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(publish_existing_articles, migrations.RunPython.noop),
    ]
