# Generated by Django 5.2.13 on 2026-08-30 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_articlevote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Article submitted'), ('approved', 'Article approved'), ('rejected', 'Article rejected'), ('edit_submitted', 'Edit submitted'), ('edit_approved', 'Edit approved'), ('edit_rejected', 'Edit rejected'), ('deleted', 'Article deleted')], max_length=32)),
                ('target_title', models.CharField(max_length=200)),
                ('target_slug', models.SlugField(blank=True, max_length=220)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_log_entries', to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_log_entries', to='wiki.article')),
            ],
            options={
                'verbose_name': 'Moderation log entry',
                'verbose_name_plural': 'Moderation log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='wiki_modera_created_5ef4df_idx')],
            },
        ),
    ]
