# Generated by Django 5.2.13 on 2026-08-31 13:56

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_moderationlogentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlevote',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Article vote', 'verbose_name_plural': 'Article votes'},
        ),
        migrations.AddField(
            model_name='article',
            name='today',
            field=models.DateField(default=datetime.date(2026, 8, 31)),
        ),
        migrations.AddField(
            model_name='article',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='viewed_today',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
