# Generated by Django 5.2.13 on 2026-08-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('introduction', models.CharField(max_length=500)),
                ('body_text', models.CharField()),
                ('image', models.ImageField(upload_to='')),
                ('creation_date', models.DateTimeField()),
            ],
        ),
    ]
